# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=5)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.IntegerField()),
                ('year', models.CharField(max_length=2)),
                ('hometown', models.CharField(max_length=50)),
                ('bio_page', models.CharField(max_length=200)),
            ],
        ),
    ]
